[project]
name = "srm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.0.0",
    "lighteval[vllm]>=0.7.0",
    "vllm>=0.6.0",
    "torch>=2.0.0",
    "transformers>=4.45.0",
    "accelerate>=0.25.0",
]
